### PR TITLE
add shouldFail

### PR DESCRIPTION
**Pull request by mwotton**
this solves https://github.com/hspec/hspec/issues/304 - hopefully it's along the lines you intended, @sol .

### CODE REVIEW

**Comment by sol** [comment]
@mwotton contrary to what I said over 3 years ago in #304, I'm puzzled if we should add this to `hspec-contrib` instead (at least for now).  What do you think?

(read: Is this functionality require by enough users so that it warrants increasing the API surface for everybody?)

**Comment by mwotton** [comment]
i think hspec-contrib is more suitable, but that would require exposing mapSpecItem_, no?

**Comment by mwotton** [comment]
really, the only people who need this functionality are writing tests-for-tests, and to be completely honest if mapSpecItem_ was available i probably would have just written it as a private function and forgotten to PR it :)

**Comment by sol** [comment]
@mwotton `mapSpecItem_` is re-exported from `Test.Hspec.Core.Spec`.

https://hackage.haskell.org/package/hspec-core-2.7.4/docs/Test-Hspec-Core-Spec.html#v:mapSpecItem_

Keep it as a private function, or open a PR for `hspec-contrib`, whatever is more convenient for you ;).

**Comment by mwotton** [comment]
oh duh, i must have misread :) cheers, i'll open a PR later.

**Pull request closed without merging**
