### PR TITLE
Deprecate captureLogs

### PR DESCRIPTION
**Pull request by jkarni**

### CODE REVIEW

**Comment by jkarni** [comment]
See https://github.com/hspec/mockery/pull/2/files

**Comment by sol** [comment]
@jkarni I ended up moving the warning to the module, so that even an unused import will generate a warning.

**Comment by sol** [comment]
https://github.com/hspec/hspec/commit/f30eb0ece13d38c85c0c57eab6d0713928f16ed8

**Comment by sol** [comment]
On hackage.

**Pull request merged**
