### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by askeblad**
hspec-core/vendor/Control/Concurrent/Async.hs

### CODE REVIEW

**Comment by sol** [comment]
@askeblad bot commits should be marked as such.

**Comment by askeblad** [comment]
@sol the commit displays a "Verified"  button which GitHub added

here's the fix if a Member would implement the change themself (then I would delete my fork)

hspec-core/vendor/Control/Concurrent/Async.hs

```diff
- -- Like for 'forkIO', the action may be left running unintentinally
+ -- Like for 'forkIO', the action may be left running unintentionally
```

**Comment by Mikolaj** [comment]
How do you know this is a bot? Asking seriously, because I've spent a lot of time conversing with this entity (and it wasn't all that unpleasant) and I'd like to be better at spotting an AI next time.

**Comment by sol** [comment]
This issue tracker is not the right place for irony.

https://github.com/hspec/HUnit/pull/52#issuecomment-1079722448

**Pull request closed without merging**
