### PR TITLE
docs: add an example for `around`

### PR DESCRIPTION
**Pull request by soenkehahn**

### CODE REVIEW

**Comment by sol** [comment]
LGTM

**Comment by soenkehahn** [comment]
@sol: Re the travis failures: We seem to have the same failures on `master`. Should I merge this then?

**Comment by soenkehahn** [comment]
Well, I guess it can't hurt to merge this docs change...

**Comment by sol** [comment]
To get the doc changes only you would still need to copy the generated html to this repo:

https://github.com/hspec/hspec.github.io/

**Pull request merged**
