### PR TITLE
Extract source locations from `NoMethodError` and `AssertionFailed`

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@parsonsmatt apparently travis-ci.com jobs are not running anymore because we are out of "credits" :/

**Comment by sol** [comment]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by parsonsmatt** [comment]
I've switched projects I control over to GItHub Actions, and it works well. [This is what we have for `persistent`](https://github.com/yesodweb/persistent/blob/master/.github/workflows/haskell.yml).

**Review by parsonsmatt — APPROVED** [review]
Looks great!

**Pull request merged**
