### PR TITLE
docs: add favicon

### LINKED ISSUE #887: docs: Add favicon / shortcut icon

### PR DESCRIPTION
**Pull request by JoranVanBelle**
fixes #887 

@sol, I added a link to every html-file including the hspec-logo.
Locally the favicon seems to be in place

### CODE REVIEW

**Comment by sol** [comment]
@JoranVanBelle thanks for looking into this. This needs to go into https://github.com/hspec/hspec/blob/main/doc/_layouts/default.html.

**Comment by sol** [comment]
What is the state of shortcut icons?  Is it possible in 2024 to go with PNG only?  If yes, can we deep link to https://avatars.githubusercontent.com/u/1610185?s=400&v=4? (`s` can be adjusted to any size we need)

Do we need extra stuff for iOS devices, etc.?

**Comment by JoranVanBelle** [comment]
@sol, I removed the tag from the default.html and added a tag for ios support

**Comment by JoranVanBelle** [comment]
Messed up history -> this should be better: [https://github.com/hspec/hspec/pull/903](https://github.com/hspec/hspec/pull/903)

**Pull request closed without merging**
