### PR TITLE
Suppress excessive diff output

### LINKED ISSUE #449: Suppress excessive diff output
https://github.com/hspec/hspec-expectations/issues/30

### PR DESCRIPTION
**Pull request by sol**
- [x] Add a flag to disable (`--diff-context=full`)
- [x] Suppress identical lines within the text, not only at the start/end
- [x] Never omit less than 3 lines

(close #449)

#### before:
before
#### after (with #715):
after
#### after (without #715):
after

### CODE REVIEW

**Comment by sol** [comment]
@chshersh you originally requested this in https://github.com/hspec/hspec-expectations/issues/30.  If you have any input regarding the output formatting then please let me know.  I'm not sure yet if #715 is essential, or if we can do without it.

**Comment by chshersh** [comment]
Hi @sol, this looks fantastic 👏🏻 I don't have any specific input on the output formatting.

I believe we can do without #715. But to my taste it looks better with less indentation because lines can become quite long and it looks nicer when a single line from the origin doesn't span multiple lines in the test output (assuming having the same width for my source and terminal).

**Comment by sol** [comment]
This is the ready to go. I’m going to deal with #715 as a separate story.

**Comment by parsonsmatt** [comment]
Oh that's really nice 👍🏻

**Pull request merged**
